"""
emailer.py
Member 4 (Integration) | Thursday deliverable.

Sends maintenance alerts and reports over Gmail SMTP.

Credentials are never stored in the repository: the app password is read
from the EMAIL_PASS environment variable at send time (put it in a local
.env file, which .gitignore already excludes). With no password set the
module falls back to DRY RUN — the message is printed instead of sent, so
the GUI can be demonstrated on a machine without mail credentials.

Gmail needs a 16-character App Password (Google account -> Security ->
2-Step Verification -> App passwords); a normal account password is
rejected by SMTP.
"""

import os
import smtplib
from email.message import EmailMessage

from config import SENDER_EMAIL, SMTP_HOST, SMTP_PORT, TECH_EMAIL

# Loading .env is optional: python-dotenv may not be installed on a
# marker's machine, and the app must still start without it.
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass


def get_password():
    """Return the SMTP app password, or None when the app is unconfigured."""
    return os.environ.get('EMAIL_PASS')


def is_configured() -> bool:
    """True when a real send is possible; the GUI uses this to warn the user."""
    return bool(get_password())


def build_message(to_email, subject, body, attachment_path=None):
    """Assemble a MIME message, optionally carrying a report as a .txt file."""
    message = EmailMessage()
    message['From'] = SENDER_EMAIL
    message['To'] = to_email
    message['Subject'] = subject
    message.set_content(body)

    if attachment_path:
        with open(attachment_path, 'rb') as f:
            data = f.read()
        # maintype/subtype must be given explicitly — EmailMessage does not
        # guess the type, and a wrong type makes clients hide the file.
        message.add_attachment(
            data, maintype='text', subtype='plain',
            filename=os.path.basename(attachment_path),
        )

    return message


def send_email(to_email, subject, body, attachment_path=None) -> str:
    """Send one message and return a human-readable status for the GUI.

    Any SMTP failure is turned into a returned string rather than an
    exception, because this is called from button handlers where an
    uncaught error would kill the event loop.
    """
    message = build_message(to_email, subject, body, attachment_path)
    password = get_password()

    if not password:
        # DRY RUN: no credentials configured. Echo the message so the demo
        # still shows exactly what would have been delivered.
        print('[DRY RUN] EMAIL_PASS not set — message not sent.')
        print(f'  To      : {to_email}')
        print(f'  Subject : {subject}')
        print(f'  Attach  : {attachment_path or "none"}')
        return f'DRY RUN — no EMAIL_PASS configured. Would email {to_email}.'

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=20) as server:
            server.starttls()  # upgrade to TLS before sending credentials
            server.login(SENDER_EMAIL, password)
            server.send_message(message)
        return f'Email sent to {to_email}.'
    except smtplib.SMTPAuthenticationError:
        return ('Login rejected by Gmail. EMAIL_PASS must be a 16-character '
                'App Password, not the account password.')
    except Exception as error:
        return f'Email failed: {error}'


def send_alert(well_id, risk_score, report_path=None) -> str:
    """FR4: notify the technical team that a well crossed RISK_THRESHOLD."""
    subject = f'CRITICAL: Predicted pump failure on {well_id}'
    body = (
        f'Automated alert from the Digital Oilfield Monitoring System.\n\n'
        f'Well              : {well_id}\n'
        f'Predicted failure : {risk_score * 100:.1f}%\n\n'
        f'The model classifies this well as CRITICAL. Schedule an inspection '
        f'before the next production day.\n\n'
        f'-- Squad Charlie monitoring system'
    )
    return send_email(TECH_EMAIL, subject, body, report_path)


def send_report(to_email, well_id, report_kind, report_path) -> str:
    """Email a generated technical or stakeholder report as an attachment."""
    subject = f'{report_kind} report — {well_id}'
    body = (
        f'Attached is the {report_kind.lower()} report for {well_id}, '
        f'generated by the Digital Oilfield Monitoring System.'
    )
    return send_email(to_email, subject, body, report_path)


if __name__ == "__main__":
    # Prints the dry-run preview unless EMAIL_PASS is exported.
    print('Configured:', is_configured())
    print(send_alert('WELL-01', 0.91))
